plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.group

base {
	archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven { url = "https://repo.hypixel.net/repository/Hypixel/" }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"scathapro" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

    runs {
        remove server
    }

    log4jConfigs.from file("log4j.xml")
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    runtimeOnly "me.djtheredstoner:DevAuth-fabric:${project.devauth_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "net.hypixel:mod-api:${project.hypixel_mod_api_version}"
    var hypixelModApiBuildDependency = "maven.modrinth:hypixel-mod-api:${project.hypixel_mod_api_build_version}"
    clientRuntimeOnly hypixelModApiBuildDependency
    include hypixelModApiBuildDependency
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand (inputs.properties) {
            escapeBackslash = true
        }
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 26
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}
