# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.2.2
group=namelessju.scathapro
archives_base_name=scathapro

# Dependencies
devauth_version=1.2.2
fabric_api_version=0.152.1+26.2
modmenu_version=20.0.1
hypixel_mod_api_version=1.0.2
hypixel_mod_api_build_version=1.0.2+build.1+mc26.1