mod.id = "scathapro"
mod.name = "Scatha-Pro"
mod.group = "namelessju.scathapro"
mod.version = "2.4"

deps.fabric_loader = "0.19.5"
loomx.loom_version = "1.17-SNAPSHOT"

["26.3"]
mod.mc_compat = ">=26.3"
mod.mc_releases = ["26.3"]
deps.devauth = "1.2.2"
deps.fabric_api = "0.160.6+26.3"
deps.modmenu = "21.0.0-beta.1"
deps.hypixel_mod_api = "1.0.2"
deps.hypixel_mod_api_build = "1.0.2+build.1+mc26.1"

["26.2"]
mod.mc_compat = "26.2"
mod.mc_releases = ["26.2"]
deps.devauth = "1.2.2"
deps.fabric_api = "0.160.0+26.2"
deps.modmenu = "20.0.2"
deps.hypixel_mod_api = "1.0.2"
deps.hypixel_mod_api_build = "1.0.2+build.1+mc26.1"

["26.1.2"]
mod.mc_compat = ">=26.1 <=26.1.2"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
deps.devauth = "1.2.2"
deps.fabric_api = "0.155.3+26.1.2"
deps.modmenu = "18.0.1"
deps.hypixel_mod_api = "1.0.2"
deps.hypixel_mod_api_build = "1.0.2+build.1+mc26.1"